name: CI
on: [push, pull_request]
jobs:

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Check out git tree
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6.7'
          bundler-cache: true
      - name: Run rubocop
        run: bundle exec rubocop

  rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Check out git tree
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6.7'
          bundler-cache: true
      - name: Run RSpec tests
        run: bundle exec rake

